---
version: '3.3'

services:
  base:
    image: bee-travels/node-base:v1
    build: .

  jaeger:
    image: jaegertracing/all-in-one:1.7
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - 8081:8081

  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always

  couch:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin

  destination-data-gen:
    depends_on:
      - couch
      - postgres
      - mongo
    image: beetravels/data-gen-destination:13de064f6409e9aec5db244a6a9b4e65b7e11623
    restart: on-failure
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=admin
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CONNECTION_URL=http://admin:admin@couch:5984
      - GENERATE_DATA=false
      - DATABASE=${DATABASE}

  hotel-data-gen:
    depends_on:
      - couch
      - postgres
      - mongo
    image: beetravels/data-gen-hotel:13de064f6409e9aec5db244a6a9b4e65b7e11623
    restart: on-failure
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=admin
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CONNECTION_URL=http://admin:admin@couch:5984
      - GENERATE_DATA=false
      - DATABASE=${DATABASE}

  cars-data-gen:
    depends_on:
      - couch
      - postgres
      - mongo
    image: beetravels/data-gen-carrental:13de064f6409e9aec5db244a6a9b4e65b7e11623
    restart: on-failure
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=admin
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CONNECTION_URL=http://admin:admin@couch:5984
      - GENERATE_DATA=false
      - DATABASE=${DATABASE}

  flights-data-gen:
    depends_on:
      - couch
      - postgres
      - mongo
    image: beetravels/data-gen-airports:13de064f6409e9aec5db244a6a9b4e65b7e11623
    restart: on-failure
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=admin
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CONNECTION_URL=http://admin:admin@couch:5984
      - GENERATE_DATA=false
      - DATABASE=${DATABASE}

  destination:
    build: services/destination-v2
    ports:
      - "9001:9001"
    depends_on:
      - base
    environment:
      - DATABASE=${DATABASE}
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=admin

  hotel:
    build: services/hotel-v2
    ports:
      - "9101:9101"
    depends_on:
      - base
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE=${DATABASE}
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=admin

  car-rental:
    build: services/car-rental-v2
    ports:
      - "9102:9102"
    depends_on:
      - base
      - cars-data-gen
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE=${DATABASE}
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=admin

  flights:
    build: services/flights-v2
    ports:
      - "9103:9103"
    depends_on:
      - base
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE=${DATABASE}
      - MONGO_CONNECTION_URL=mongodb://admin:admin@mongo:27017
      - COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=admin

  currency-exchange:
    build: services/currency-exchange
    ports:
      - "9201:9201"
    depends_on:
      - base

  email-service:
    build: services/email-v2
    ports:
      - "9301:9301"
    depends_on:
      - base
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

  payment:
    build: services/payment-v2
    ports:
      - "9403:9403"
    depends_on:
      - base

  checkout:
    build: services/checkout-v2
    ports:
      - "9402:9402"
    depends_on:
      - base
      - postgres
      - payment
      - email-service
    environment:
      - DATABASE=${DATABASE}
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PAYMENT_URL=http://payment:9403
      - EMAIL_URL=http://email-service:9301

  ui:
    build: services/ui
    ports:
      - "9000:9000"
    depends_on:
      - base
      - destination
      - hotel
      - car-rental
      - currency-exchange
      - flights
    environment:
      - NODE_ENV=production
      - DESTINATION_URL=http://destination:9001
      - HOTEL_URL=http://hotel:9101
      - CAR_URL=http://car-rental:9102
      - CURRENCY_EXCHANGE_URL=http://currency-exchange:9201
      - FLIGHTS_URL=http://flights:9103
